//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Attraction = new HashSet<Attraction>();
            this.Comment = new HashSet<Comment>();
            this.Message = new HashSet<Message>();
            this.Travel = new HashSet<Travel>();
        }
    
        public int user_Id { get; set; }
        public string userAccount { get; set; }
        public string userPassword { get; set; }
        public string userPhone { get; set; }
        public string userAddress { get; set; }
        public string userEmail { get; set; }
        public string userPhoto { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public Nullable<int> roleAdmin { get; set; }
        public Nullable<int> attractionOwner { get; set; }
        public string travelOwner { get; set; }
        public string searchLog { get; set; }
        public string loginLog { get; set; }
        public string OrderLog { get; set; }
        public string cart { get; set; }
        public string userComment { get; set; }
        public string userFavorite { get; set; }
        public string userMessage { get; set; }
        public System.Guid email_ID { get; set; }
        public string email_Approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attraction> Attraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travel> Travel { get; set; }
    }
}
