//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int msg_Id { get; set; }
        public Nullable<int> user_Id { get; set; }
        public Nullable<int> attr_Id { get; set; }
        public string QA { get; set; }
        public string message1 { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Attraction Attraction { get; set; }
    }
}
