//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Travel()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int travel_Id { get; set; }
        public string DATA { get; set; }
        public Nullable<int> travelOwner { get; set; }
        public string travelCover { get; set; }
        public string userFavorite { get; set; }
        public string travelInfo { get; set; }
        public Nullable<System.DateTime> travelDate { get; set; }
        public string travelCity { get; set; }
        public string travelType { get; set; }
        public string travelComment { get; set; }
        public string travelRate { get; set; }
        public string attractionReferral { get; set; }
        public string travelTitle { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
